//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 

namespace AlbumPanelColorTiles.Base
{

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
   public partial class Panels
   {

      private Panel[] panelField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Panel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Panel[] Panel
      {
         get
         {
            return this.panelField;
         }
         set
         {
            this.panelField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Panel
   {

      private Gab gabField;

      private Cheeks cheeksField;

      private Windows windowsField;

      private Balconys balconysField;

      private Undercuts undercutsField;

      private Outsides outsidesField;

      private string markField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Gab gab
      {
         get
         {
            return this.gabField;
         }
         set
         {
            this.gabField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Cheeks cheeks
      {
         get
         {
            return this.cheeksField;
         }
         set
         {
            this.cheeksField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Windows windows
      {
         get
         {
            return this.windowsField;
         }
         set
         {
            this.windowsField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Balconys balconys
      {
         get
         {
            return this.balconysField;
         }
         set
         {
            this.balconysField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Undercuts undercuts
      {
         get
         {
            return this.undercutsField;
         }
         set
         {
            this.undercutsField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Outsides outsides
      {
         get
         {
            return this.outsidesField;
         }
         set
         {
            this.outsidesField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string mark
      {
         get
         {
            return this.markField;
         }
         set
         {
            this.markField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Gab
   {

      private double lengthField;

      private double heightField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double length
      {
         get
         {
            return this.lengthField;
         }
         set
         {
            this.lengthField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double height
      {
         get
         {
            return this.heightField;
         }
         set
         {
            this.heightField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Cheeks
   {

      private string cheekField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string cheek
      {
         get
         {
            return this.cheekField;
         }
         set
         {
            this.cheekField = value.Trim();
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Windows
   {

      private Window[] windowField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("window", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Window[] window
      {
         get
         {
            return this.windowField;
         }
         set
         {
            this.windowField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Window
   {

      private double widthField;

      private double heightField;

      private Posi posiField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double width
      {
         get
         {
            return this.widthField;
         }
         set
         {
            this.widthField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double height
      {
         get
         {
            return this.heightField;
         }
         set
         {
            this.heightField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Posi posi
      {
         get
         {
            return this.posiField;
         }
         set
         {
            this.posiField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Posi
   {

      private double xField;

      private double yField;

      private double zField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double X
      {
         get
         {
            return this.xField;
         }
         set
         {
            this.xField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double Y
      {
         get
         {
            return this.yField;
         }
         set
         {
            this.yField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double Z
      {
         get
         {
            return this.zField;
         }
         set
         {
            this.zField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Balconys
   {

      private Balcony[] balconyField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("balcony", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Balcony[] balcony
      {
         get
         {
            return this.balconyField;
         }
         set
         {
            this.balconyField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Balcony
   {

      private double widthField;

      private double heightField;

      private Posi posiField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double width
      {
         get
         {
            return this.widthField;
         }
         set
         {
            this.widthField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double height
      {
         get
         {
            return this.heightField;
         }
         set
         {
            this.heightField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Posi posi
      {
         get
         {
            return this.posiField;
         }
         set
         {
            this.posiField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Undercuts
   {

      private Undercut[] undercutField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("undercut", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Undercut[] undercut
      {
         get
         {
            return this.undercutField;
         }
         set
         {
            this.undercutField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Undercut
   {

      private double widthField;

      private double heightField;

      private Posi posiField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double width
      {
         get
         {
            return this.widthField;
         }
         set
         {
            this.widthField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double height
      {
         get
         {
            return this.heightField;
         }
         set
         {
            this.heightField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Posi posi
      {
         get
         {
            return this.posiField;
         }
         set
         {
            this.posiField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Outsides
   {

      private Outside[] outsideField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("outside", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Outside[] outside
      {
         get
         {
            return this.outsideField;
         }
         set
         {
            this.outsideField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Outside
   {

      private double widthField;

      private double heightField;

      private Posi posiField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double width
      {
         get
         {
            return this.widthField;
         }
         set
         {
            this.widthField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public double height
      {
         get
         {
            return this.heightField;
         }
         set
         {
            this.heightField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Posi posi
      {
         get
         {
            return this.posiField;
         }
         set
         {
            this.posiField = value;
         }
      }
   }
}